packages:
  - apps/*
  - packages/*

catalog:
  "@types/bun": ^1.3.8
  croner: ^9.1.0
  drizzle-orm: beta
  graphql: ^16.9.0
  jose: ^5.10.0
  pino: ^9.6.0
  postgres: ^3.4.5
  typescript: ^5.7.3
  zod: ^3.24.1
  luxon: ^3.7.2
  "@types/luxon": ^3.7.1

onlyBuiltDependencies:
  - esbuild
