packages:
  - apps/*
  - packages/*

catalog:
  "@types/bun": ^1.3.8
  croner: ^10.0.1
  drizzle-orm: beta
  graphql: ^16.13.0
  jose: ^6.1.3
  pino: ^10.3.1
  postgres: ^3.4.5
  typescript: ^5.7.3
  zod: ^4.3.6
  luxon: ^3.7.2
  "@types/luxon": ^3.7.1

onlyBuiltDependencies:
  - esbuild
